# -*- coding: utf-8 -*-
"""smart-message-guardian.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CRCRdqqioSPGqSNlJ4lpcTL88MiDsX7r
"""

# Install dependencies & download cloudflared
!pip install flask -q
!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
!dpkg -i cloudflared-linux-amd64.deb > /dev/null
!pkill cloudflared

import os, re, time, zipfile, urllib.request, subprocess
import pandas as pd
import numpy as np
import tensorflow as tf
from flask import Flask, request, jsonify, render_template_string
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Bidirectional, LSTM, Dense, Dropout

# ==========================================
# 1. DOWNLOAD DATASET & AUGMENT (INCLUDING THREATS)
# ==========================================
print("📥 Fetching dataset...")
DATA_URL = "https://archive.ics.uci.edu/static/public/228/sms+spam+collection.zip"
urllib.request.urlretrieve(DATA_URL, "sms.zip")
with zipfile.ZipFile("sms.zip", 'r') as z:
    z.extractall(".")

df = pd.read_csv("SMSSpamCollection", sep="\t", header=None, names=["label", "message"])
df["label"] = df["label"].map({"ham": 0, "spam": 1})

# Added financial scams + physical threats
modern_scams = [
    (1, "Dear customer your SBI bank account is blocked. Update your PAN card immediately at http://bit.ly/sbi-pan"),
    (1, "URGENT: Electricity power will be disconnected tonight at 9:30 PM due to unpaid bill. Call officer at 9876543210"),
    (1, "Congratulations! You have won lottery cash ₹25,00,000 in KBC. Contact manager on WhatsApp now."),
    (1, "India Post: Your package delivery failed due to incomplete address. Update here: http://bit.ly/indiapost-track"),
    (1, "Hi Mum, my phone dropped in water and is broken. This is my new temporary number. Please WhatsApp me urgently."),
    (1, "I will kill you right now. Watch your back."),
    (1, "Send the money or I will hurt your family."),
    (0, "Hi Dad, I will reach home by 8 PM today for dinner."),
    (0, "Your OTP for login is 482910. Valid for 10 minutes."),
    (0, "Amazon: Your package will be delivered today by 9 PM. Track at amazon.in/orders")
]
df_aug = pd.concat([df, pd.DataFrame(modern_scams, columns=["label", "message"])], ignore_index=True)

# ==========================================
# 2. TOKENIZE & TRAIN BI-LSTM
# ==========================================
MAX_WORDS, MAX_LEN = 6000, 100
tokenizer = Tokenizer(num_words=MAX_WORDS, oov_token="<OOV>")
tokenizer.fit_on_texts(df_aug["message"].values)

X = tokenizer.texts_to_sequences(df_aug["message"].values)
X = pad_sequences(X, maxlen=MAX_LEN, padding="post")
y = df_aug["label"].values

print("🧠 Training Bi-LSTM Model...")
model = Sequential([
    Embedding(MAX_WORDS, 64),
    Bidirectional(LSTM(32)),
    Dropout(0.3),
    Dense(16, activation="relu"),
    Dense(1, activation="sigmoid")
])
model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])
model.fit(X, y, epochs=3, batch_size=64, verbose=0)
print("✅ Bi-LSTM ready!")

# ==========================================
# 3. WEB APP FRONTEND (HTML/JS)
# ==========================================
app = Flask(__name__)

HTML_PAGE = """
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AI Smart Message Guardian</title>
    <style>
        body { font-family: -apple-system, Roboto, sans-serif; background: #0f172a; color: #fff; margin: 0; padding: 15px; }
        .card { background: #1e293b; border-radius: 16px; padding: 20px; box-shadow: 0 4px 20px rgba(0,0,0,0.4); max-width: 450px; margin: auto; }
        h2 { margin-top: 0; color: #38bdf8; font-size: 20px; text-align: center; }
        p.sub { font-size: 13px; color: #94a3b8; text-align: center; margin-bottom: 20px; }
        textarea { width: 100%; box-sizing: border-box; height: 90px; border-radius: 10px; border: 1px solid #334155; background: #0f172a; color: #fff; padding: 10px; font-size: 14px; margin-bottom: 10px;}
        button.primary { width: 100%; background: #2563eb; color: #fff; border: none; padding: 12px; border-radius: 10px; font-size: 15px; font-weight: bold; cursor: pointer; }
        .preset-btns { display: grid; grid-template-columns: 1fr; gap: 6px; margin-bottom: 15px; max-height: 220px; overflow-y: auto; padding-right: 5px;}
        .btn-preset { background: #334155; color: #cbd5e1; border: none; padding: 10px; border-radius: 8px; font-size: 12px; text-align: left; cursor: pointer; transition: background 0.2s;}
        .btn-preset:active { background: #475569; }
        #resultBox { display: none; margin-top: 20px; padding: 15px; border-radius: 12px; }
        .danger { background: #7f1d1d; border: 2px solid #ef4444; }
        .safe { background: #064e3b; border: 2px solid #10b981; }
        .score { font-size: 24px; font-weight: bold; margin-top: 5px; }
        ::-webkit-scrollbar { width: 6px; }
        ::-webkit-scrollbar-thumb { background: #475569; border-radius: 10px; }
    </style>
</head>
<body>
    <div class="card">
        <h2>🛡️ Message Guardian</h2>
        <p class="sub">Elderly Protection System (Bi-LSTM Model)</p>

        <label style="font-size: 12px; color: #94a3b8; display: block; margin-bottom: 5px;">SCAM SIMULATION PRESETS:</label>
        <div class="preset-btns">
            <button class="btn-preset" onclick="fill('URGENT: Your SBI bank account is blocked. Update KYC immediately at http://bit.ly/sbi-kyc')">🔴 1. Bank Impersonation / KYC</button>
            <button class="btn-preset" onclick="fill('Electricity power will be disconnected tonight at 9:30 PM due to unpaid bill. Call 9876543210')">🔴 2. Utility Disconnection Scam</button>
            <button class="btn-preset" onclick="fill('I will kill you right now if you dont send money.')">🔴 3. Physical Threat / Extortion</button>
            <button class="btn-preset" onclick="fill('India Post: Your package delivery failed due to incomplete address. Update here: http://bit.ly/indiapost-track')">🔴 4. Postal / Package Scam</button>
            <button class="btn-preset" onclick="fill('Congratulations! Your mobile number won ₹25,00,000 in KBC Jio lottery. Send Aadhaar to claim prize.')">🔴 5. KBC Lottery Scam</button>
            <button class="btn-preset" onclick="fill('Hi Mum, my phone dropped in water and is broken. This is my new temporary number. Please WhatsApp me urgently.')">🔴 6. Family Emergency Scam</button>
            <button class="btn-preset" onclick="fill('Amazon: Your package will be delivered today by 9 PM. Track at amazon.in/orders')">🟢 7. Safe: Genuine Tracking</button>
            <button class="btn-preset" onclick="fill('Hi Dad, I will reach home by 8 PM today for dinner.')">🟢 8. Safe: Normal Family Text</button>
        </div>

        <textarea id="msgInput" placeholder="Paste or type SMS here..."></textarea>
        <button class="primary" onclick="analyze()">⚡ Detect Threat</button>

        <div id="resultBox">
            <div id="riskBadge" style="font-weight: bold; font-size: 16px;"></div>
            <div id="scoreText" class="score"></div>
            <p id="actionText" style="font-size: 13px; margin-bottom: 0;"></p>
        </div>
    </div>

    <script>
        function fill(text) {
            document.getElementById('msgInput').value = text;
            document.getElementById('resultBox').style.display = 'none';
        }

        function speak(text) {
            if ('speechSynthesis' in window) {
                window.speechSynthesis.cancel();
                var utterance = new SpeechSynthesisUtterance(text);
                utterance.rate = 0.9;
                window.speechSynthesis.speak(utterance);
            }
        }

        async function analyze() {
            var msg = document.getElementById('msgInput').value.trim();
            if (!msg) return alert('Enter a message!');

            var btn = document.querySelector('.primary');
            btn.innerText = '⏳ Scanning...';

            try {
                var res = await fetch('/predict', {
                    method: 'POST',
                    headers: {'Content-Type': 'application/json'},
                    body: JSON.stringify({message: msg})
                });
                var data = await res.json();

                var box = document.getElementById('resultBox');
                box.style.display = 'block';

                if (data.risk === 'HIGH') {
                    box.className = 'danger';
                    document.getElementById('riskBadge').innerText = '🚨 HIGH RISK DETECTED (BLOCKED)';
                    document.getElementById('scoreText').innerText = data.probability + '% Scam/Threat Probability';
                    document.getElementById('actionText').innerText = 'Action: Notification Suppressed & Voice Alarm Fired.';
                } else {
                    box.className = 'safe';
                    document.getElementById('riskBadge').innerText = '🟢 SAFE MESSAGE';
                    document.getElementById('scoreText').innerText = data.probability + '% Scam/Threat Probability';
                    document.getElementById('actionText').innerText = 'Action: Delivered Normally to Inbox.';
                }

                speak(data.voice_alert);
            } catch (err) {
                alert('Connection error. Is Colab still running?');
            } finally {
                btn.innerText = '⚡ Detect Threat';
            }
        }
    </script>
</body>
</html>
"""

# ==========================================
# 4. FLASK API BACKEND
# ==========================================
@app.route("/")
def home():
    return render_template_string(HTML_PAGE)

@app.route("/predict", methods=["POST"])
def predict():
    data = request.get_json(force=True)
    msg = data.get("message", "")

    # NLP Sequence prediction
    seq = tokenizer.texts_to_sequences([msg])
    padded = pad_sequences(seq, maxlen=MAX_LEN, padding="post")
    prob = float(model.predict(padded, verbose=0)[0][0])

    # Heuristics & Rules
    has_link = bool(re.search(r'(http://|https://|bit\.ly|tinyurl|\.apk)', msg, re.IGNORECASE))
    has_urgency = bool(re.search(r'(urgent|immediately|blocked|tonight|suspended|broken)', msg, re.IGNORECASE))
    has_threat = bool(re.search(r'(kill|hurt|murder|die|attack)', msg, re.IGNORECASE))

    if has_link and prob > 0.35:
        prob = min(prob + 0.20, 0.99)
    if has_urgency and prob > 0.35:
        prob = min(prob + 0.15, 0.99)

    # Instantly flag physical threats
    if has_threat:
        prob = max(prob, 0.96)

    # Thresholding
    if prob >= 0.75:
        risk = "HIGH"
        voice_alert = "Warning! Dangerous message detected. Do not click any links."
    else:
        risk = "SAFE"
        voice_alert = "Safe message received."

    return jsonify({"risk": risk, "probability": round(prob * 100, 1), "voice_alert": voice_alert})

# ==========================================
# 5. START CLOUDFLARE PUBLIC TUNNEL
# ==========================================
def get_tunnel():
    with open("tunnel.log", "w") as f:
        subprocess.Popen(["cloudflared", "tunnel", "--url", "http://127.0.0.1:5000"], stdout=f, stderr=subprocess.STDOUT)
    time.sleep(5)
    for _ in range(15):
        time.sleep(1)
        if os.path.exists("tunnel.log"):
            with open("tunnel.log", "r") as f:
                match = re.search(r'https://[a-zA-Z0-9-]+\.trycloudflare\.com', f.read())
                if match: return match.group(0)
    return None

url = get_tunnel()
print("\n" + "="*60)
print(f"📱 OPEN THIS ON YOUR MOBILE CHROME BROWSER:\n👉 {url}")
print("="*60 + "\n")

app.run(port=5000)